In [5]:
import pandas as pd
oil_df=pd.read_csv("oil_prices.csv")
oil_df

            Date  Price
0     2020-01-02  61.17
1     2020-01-03  63.00
2     2020-01-06  63.27
3     2020-01-07  62.70
4     2020-01-08  59.65
...          ...    ...
1515  2026-01-26  60.46
1516  2026-01-27  62.04
1517  2026-01-28  62.75
1518  2026-01-29  64.77
1519  2026-01-30  64.50

[1520 rows x 2 columns]

In [3]:
from  sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/cross_market")

In [4]:
import pandas as pd

In [8]:
oil_df.to_sql("oil_price",if_exists="replace",con=engine)

1520

In [9]:
oil_df

            Date  Price
0     2020-01-02  61.17
1     2020-01-03  63.00
2     2020-01-06  63.27
3     2020-01-07  62.70
4     2020-01-08  59.65
...          ...    ...
1515  2026-01-26  60.46
1516  2026-01-27  62.04
1517  2026-01-28  62.75
1518  2026-01-29  64.77
1519  2026-01-30  64.50

[1520 rows x 2 columns]

In [10]:
import pandas as pd
hist_df=pd.read_csv("hist_prices.csv")
hist_df

            date     price_usd  coin_id
0     2025-02-20  96554.871563  bitcoin
1     2025-02-21  98384.317382  bitcoin
2     2025-02-22  96135.155413  bitcoin
3     2025-02-23  96564.154143  bitcoin
4     2025-02-24  96327.463091  bitcoin
...          ...           ...      ...
1093  2026-02-16      0.999591   tether
1094  2026-02-17      0.999630   tether
1095  2026-02-18      0.999656   tether
1096  2026-02-19      0.999661   tether
1097  2026-02-19      0.999701   tether

[1098 rows x 3 columns]

In [11]:
hist_df.to_sql("hist_prices",if_exists="replace",con=engine)

1098

In [12]:
import pandas as pd
final_df=pd.read_csv("stock_prices.csv")
final_df

,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
1,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
2,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
3,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
4,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC
...,...,...,...,...,...,...,...
4572,2026-02-02,24796.500000,25108.099609,24679.400391,25088.400391,4.492000e+05,^NSEI
4573,2026-02-03,26308.050781,26341.199219,25641.300781,25727.550781,6.373000e+05,^NSEI
4574,2026-02-04,25675.050781,25818.550781,25563.949219,25776.000000,4.298000e+05,^NSEI
4575,2026-02-05,25755.900391,25757.650391,25579.500000,25642.800781,3.438000e+05,^NSEI
4576,2026-02-06,25605.800781,25703.949219,25491.900391,25693.699219,3.755000e+05,^NSEI

In [13]:
final_df.to_sql("stock_prices",if_exists="replace",con=engine)

4577

In [14]:
import pandas as pd
records_df=pd.read_csv("records.csv")
records_df

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_update
0,bitcoin,btc,Bitcoin,6.032988e+06,120700996149603,1,3.784806e+12,1.999344e+07,1.999344e+07,11187013.00,3993.420000,2026-02-23T10:29:14.053Z
1,ethereum,eth,Ethereum,1.746200e+05,21095797080775,2,1.614587e+12,1.206924e+08,1.206924e+08,431946.00,28.130000,2026-02-23T10:29:14.538Z
2,tether,usdt,Tether,9.088000e+01,16688003444148,3,5.998349e+12,1.836242e+11,1.890912e+11,105.52,36.860000,2026-02-23T10:29:15.317Z
3,ripple,xrp,XRP,1.267200e+02,7732573358041,4,2.516788e+11,6.101858e+10,9.998571e+10,313.99,0.159343,2026-02-23T10:29:15.489Z
4,binancecoin,bnb,BNB,5.529900e+04,7540319722048,5,1.083227e+11,1.363590e+08,1.363590e+08,121422.00,2.580000,2026-02-23T10:29:13.999Z
...,...,...,...,...,...,...,...,...,...,...,...,...
495,gohome,gohome,GOHOME,7.238840e+03,3819300129,496,9.536696e+07,5.246194e+05,9.999619e+06,23754.00,7065.380000,2026-02-23T10:29:11.738Z
496,fulcrom,ful,Fulcrom,2.295050e-01,3815167884,497,2.840945e+06,1.661744e+10,2.000000e+10,3.29,0.204660,2026-02-23T10:29:11.322Z
497,apex-token-2,apex,APEX,2.759000e+01,3787718169,498,1.659178e+08,1.371750e+08,5.000000e+08,319.30,9.190000,2026-02-23T10:29:07.551Z
498,loopring,lrc,Loopring,3.040000e+00,3782578555,502,6.844295e+08,1.245991e+09,1.373873e+09,278.46,1.390000,2026-02-23T10:29:18.882Z
499,terra-luna-2,luna,Terra,5.500000e+00,3781892061,499,8.375139e+08,6.876602e+08,1.078518e+09,1466.09,4.070000,2026-02-23T10:29:14.769Z

In [15]:
records_df.to_sql("records",if_exists="replace",con=engine)

500

In [16]:
import pandas as pd

In [17]:
pd.read_sql("select * from records",con=engine)

,index,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_update
0,0,bitcoin,btc,Bitcoin,6.032988e+06,120700996149603,1,3.784806e+12,1.999344e+07,1.999344e+07,11187013.00,3993.420000,2026-02-23T10:29:14.053Z
1,1,ethereum,eth,Ethereum,1.746200e+05,21095797080775,2,1.614587e+12,1.206924e+08,1.206924e+08,431946.00,28.130000,2026-02-23T10:29:14.538Z
2,2,tether,usdt,Tether,9.088000e+01,16688003444148,3,5.998349e+12,1.836242e+11,1.890912e+11,105.52,36.860000,2026-02-23T10:29:15.317Z
3,3,ripple,xrp,XRP,1.267200e+02,7732573358041,4,2.516788e+11,6.101858e+10,9.998571e+10,313.99,0.159343,2026-02-23T10:29:15.489Z
4,4,binancecoin,bnb,BNB,5.529900e+04,7540319722048,5,1.083227e+11,1.363590e+08,1.363590e+08,121422.00,2.580000,2026-02-23T10:29:13.999Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,gohome,gohome,GOHOME,7.238840e+03,3819300129,496,9.536696e+07,5.246194e+05,9.999619e+06,23754.00,7065.380000,2026-02-23T10:29:11.738Z
496,496,fulcrom,ful,Fulcrom,2.295050e-01,3815167884,497,2.840945e+06,1.661744e+10,2.000000e+10,3.29,0.204660,2026-02-23T10:29:11.322Z
497,497,apex-token-2,apex,APEX,2.759000e+01,3787718169,498,1.659178e+08,1.371750e+08,5.000000e+08,319.30,9.190000,2026-02-23T10:29:07.551Z
498,498,loopring,lrc,Loopring,3.040000e+00,3782578555,502,6.844295e+08,1.245991e+09,1.373873e+09,278.46,1.390000,2026-02-23T10:29:18.882Z
499,499,terra-luna-2,luna,Terra,5.500000e+00,3781892061,499,8.375139e+08,6.876602e+08,1.078518e+09,1466.09,4.070000,2026-02-23T10:29:14.769Z

In [18]:
import pandas as pd
pd.read_sql("select * from oil_price",con=engine)

      index        Date  Price
0         0  2020-01-02  61.17
1         1  2020-01-03  63.00
2         2  2020-01-06  63.27
3         3  2020-01-07  62.70
4         4  2020-01-08  59.65
...     ...         ...    ...
1515   1515  2026-01-26  60.46
1516   1516  2026-01-27  62.04
1517   1517  2026-01-28  62.75
1518   1518  2026-01-29  64.77
1519   1519  2026-01-30  64.50

[1520 rows x 3 columns]

In [19]:
pd.read_sql("select * from hist_prices",con=engine)

      index        date     price_usd  coin_id
0         0  2025-02-20  96554.871563  bitcoin
1         1  2025-02-21  98384.317382  bitcoin
2         2  2025-02-22  96135.155413  bitcoin
3         3  2025-02-23  96564.154143  bitcoin
4         4  2025-02-24  96327.463091  bitcoin
...     ...         ...           ...      ...
1093   1093  2026-02-16      0.999591   tether
1094   1094  2026-02-17      0.999630   tether
1095   1095  2026-02-18      0.999656   tether
1096   1096  2026-02-19      0.999661   tether
1097   1097  2026-02-19      0.999701   tether

[1098 rows x 4 columns]

In [20]:
pd.read_sql("select * from stock_prices",con=engine)

,index,Date,Open,High,Low,Close,Volume,Ticker
0,0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
1,1,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
2,2,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
3,3,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
4,4,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC
...,...,...,...,...,...,...,...,...
4572,4572,2026-02-02,24796.500000,25108.099609,24679.400391,25088.400391,4.492000e+05,^NSEI
4573,4573,2026-02-03,26308.050781,26341.199219,25641.300781,25727.550781,6.373000e+05,^NSEI
4574,4574,2026-02-04,25675.050781,25818.550781,25563.949219,25776.000000,4.298000e+05,^NSEI
4575,4575,2026-02-05,25755.900391,25757.650391,25579.500000,25642.800781,3.438000e+05,^NSEI
4576,4576,2026-02-06,25605.800781,25703.949219,25491.900391,25693.699219,3.755000e+05,^NSEI

(part_I)query_1   Find the top 3 cryptocurrencies by market cap.

In [21]:
top_3_cryptocurrencies=pd.read_sql("select* from records order by market_cap_rank  limit 3",engine)

In [22]:
top_3_cryptocurrencies

,index,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_update
0,0,bitcoin,btc,Bitcoin,6032988.00,120700996149603,1,3.784806e+12,1.999344e+07,1.999344e+07,11187013.00,3993.42,2026-02-23T10:29:14.053Z
1,1,ethereum,eth,Ethereum,174620.00,21095797080775,2,1.614587e+12,1.206924e+08,1.206924e+08,431946.00,28.13,2026-02-23T10:29:14.538Z
2,2,tether,usdt,Tether,90.88,16688003444148,3,5.998349e+12,1.836242e+11,1.890912e+11,105.52,36.86,2026-02-23T10:29:15.317Z

In [23]:
pd.read_sql("select  id, name, market_cap from records order by  market_cap desc limit 5",engine)

            id      name       market_cap
0      bitcoin   Bitcoin  120700996149603
1     ethereum  Ethereum   21095797080775
2       tether    Tether   16688003444148
3       ripple       XRP    7732573358041
4  binancecoin       BNB    7540319722048

query-2 List all coins where circulating supply exceeds 90% of total supply.

In [24]:
pd.read_sql("select* from records where (circulating_supply*100/total_supply)>90",engine)

,index,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_update
0,0,bitcoin,btc,Bitcoin,6.032988e+06,120700996149603,1,3.784806e+12,1.999344e+07,1.999344e+07,11187013.00,3993.420000,2026-02-23T10:29:14.053Z
1,1,ethereum,eth,Ethereum,1.746200e+05,21095797080775,2,1.614587e+12,1.206924e+08,1.206924e+08,431946.00,28.130000,2026-02-23T10:29:14.538Z
2,2,tether,usdt,Tether,9.088000e+01,16688003444148,3,5.998349e+12,1.836242e+11,1.890912e+11,105.52,36.860000,2026-02-23T10:29:15.317Z
3,4,binancecoin,bnb,BNB,5.529900e+04,7540319722048,5,1.083227e+11,1.363590e+08,1.363590e+08,121422.00,2.580000,2026-02-23T10:29:13.999Z
4,5,usd-coin,usdc,USDC,9.088000e+01,6764194027684,6,3.812489e+11,7.442886e+10,7.449040e+10,1327.87,65.310000,2026-02-23T10:29:16.205Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,490,casper-network,cspr,Casper Network,2.781510e-01,3856393147,490,1.682797e+08,1.387866e+10,1.436794e+10,97.26,0.272128,2026-02-23T10:29:08.617Z
266,491,would,would,would,3.860000e+00,3854726891,493,9.599010e+05,9.994526e+08,9.994526e+08,59.93,0.120658,2026-02-23T10:29:16.396Z
267,492,mask-network,mask,Mask Network,3.855000e+01,3854149675,492,6.161840e+08,1.000000e+08,1.000000e+08,2999.64,36.740000,2026-02-23T10:29:15.150Z
268,494,burnedfi,burn,BurnedFi,3.101500e+02,3819712082,495,1.074347e+07,1.236466e+07,1.236466e+07,856.92,45.780000,2026-02-23T10:29:10.928Z
269,498,loopring,lrc,Loopring,3.040000e+00,3782578555,502,6.844295e+08,1.245991e+09,1.373873e+09,278.46,1.390000,2026-02-23T10:29:18.882Z

query-3 Get coins that are within 10% of their all-time-high (ATH).

In [25]:
pd.read_sql("select* from records where current_price >= 0.9 * ath",engine)

,index,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_update
0,13,usds,usds,USDS,90.86,898432798167,14,2.220188e+09,9.889121e+09,9.889121e+09,92.23,79.670000,2026-02-23T10:29:15.719Z
1,16,ethena-usde,usde,Ethena USDe,90.76,558073640857,17,1.074713e+10,6.148720e+09,6.148720e+09,92.91,78.050000,2026-02-23T10:29:10.888Z
2,21,usd1-wlfi,usd1,USD1,90.82,456349718235,22,1.693048e+11,5.023324e+09,5.023324e+09,92.17,83.750000,2026-02-23T10:29:15.919Z
3,23,dai,dai,Dai,90.87,380900604288,24,5.840342e+09,4.190418e+09,4.190418e+09,92.29,64.850000,2026-02-23T10:29:09.616Z
4,26,paypal-usd,pyusd,PayPal USD,90.88,369650169344,27,6.979316e+09,4.067584e+09,4.080760e+09,92.20,80.950000,2026-02-23T10:29:18.068Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,447,midas-mtbill,mtbill,Midas mTBILL,95.66,4385180895,447,1.053060e+03,4.584257e+07,4.584257e+07,96.83,82.020000,2026-02-23T10:21:53.455Z
78,450,paxos-standard,usdp,Pax Dollar,90.88,4322714848,452,1.130962e+09,4.756945e+07,4.756945e+07,99.13,63.230000,2026-02-23T10:29:17.928Z
79,457,sygnum-fiusd-liquidity-fund,fiusd,Sygnum FIUSD Liquidity Fund,1070703.00,4280306267,458,NaN,3.997660e+03,3.997660e+03,1083341.00,955087.000000,2026-02-23T10:25:06.336Z
80,464,resolv-rlp,rlp,Resolv Liquidity Provider Token,116.53,4146351244,464,3.557647e+07,3.558287e+07,3.558287e+07,118.41,86.560000,2026-02-23T10:29:18.757Z
81,480,singularry,singularry,Singularry,4.00,3994228662,481,9.372156e+07,9.998975e+08,9.998975e+08,4.15,0.047119,2026-02-23T10:29:19.120Z

query-4 Find the average market cap rank of coins with volume above $1B.

In [26]:
pd.read_sql("select id,market_cap_rank from records where total_volume > 1000000000",engine)

                      id  market_cap_rank
0                bitcoin                1
1               ethereum                2
2                 tether                3
3                 ripple                4
4            binancecoin                5
..                   ...              ...
179                 zama              457
180               popcat              460
181         bio-protocol              462
182  peanut-the-squirrel              466
183             espresso              487

[184 rows x 2 columns]

query-5 Get the most recently updated coin.

In [27]:
pd.read_sql("select* from records order by last_update desc limit 1",engine)

,index,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_update
0,493,status,snt,Status,0.971179,3844710713,494,185246399.0,3.960484e+09,6.804870e+09,43.45,0.44206,2026-02-23T10:29:19.613Z

In [28]:
pd.read_sql("SHOW COLUMNS FROM records", engine)

                 Field    Type Null  Key Default Extra
0                index  bigint  YES  MUL    None
1                   id    text  YES         None
2               symbol    text  YES         None
3                 name    text  YES         None
4        current_price  double  YES         None
5           market_cap  bigint  YES         None
6      market_cap_rank  bigint  YES         None
7         total_volume  double  YES         None
8   circulating_supply  double  YES         None
9         total_supply  double  YES         None
10                 ath  double  YES         None
11                 atl  double  YES         None
12         last_update    text  YES         None

(part -II)crypto_prices (daily prices of top coins)
query1  Find the highest daily price of Bitcoin in the last 365 days.

In [29]:
pd.read_sql("SELECT MAX(price_usd) AS highest_price FROM hist_prices where coin_id='bitcoin' and date >= curdate() - interval 365 day",engine)

   highest_price
0  124773.508231

query2 Calculate the average daily price of Ethereum in the past 1 year.

In [30]:
pd.read_sql("SELECT AVG(price_usd) from hist_prices where coin_id = 'ethereum'and date >= CURDATE() - INTERVAL 1 YEAR",engine)

   AVG(price_usd)
0     3027.257805

In [31]:
pd.read_sql("SHOW COLUMNS FROM hist_prices", engine)

       Field    Type Null  Key Default Extra
0      index  bigint  YES  MUL    None
1       date    text  YES         None
2  price_usd  double  YES         None
3    coin_id    text  YES         None

Query3 Show the daily price trend of Bitcoin in January 2025. (or change the month and year according you your data)

In [32]:
pd.read_sql("select date, price_usd from hist_prices where coin_id = 'bitcoin'and date between '2025-01-01' and'2025-03-31' order by date",engine)

          date     price_usd
0   2025-02-20  96554.871563
1   2025-02-21  98384.317382
2   2025-02-22  96135.155413
3   2025-02-23  96564.154143
4   2025-02-24  96327.463091
5   2025-02-25  91396.766869
6   2025-02-26  88755.769336
7   2025-02-27  83900.114965
8   2025-02-28  84709.144778
9   2025-03-01  84441.901224
10  2025-03-02  86005.256297
11  2025-03-03  94261.532865
12  2025-03-04  86124.714187
13  2025-03-05  87310.805311
14  2025-03-06  90604.080985
15  2025-03-07  90001.400876
16  2025-03-08  86773.335976
17  2025-03-09  86142.983359
18  2025-03-10  80751.138933
19  2025-03-11  78783.940579
20  2025-03-12  82799.108029
21  2025-03-13  83884.245788
22  2025-03-14  81098.900524
23  2025-03-15  83971.709161
24  2025-03-16  84391.690876
25  2025-03-17  82610.617503
26  2025-03-18  84075.365597
27  2025-03-19  82780.030487
28  2025-03-20  86815.441095
29  2025-03-21  84270.843590
30  2025-03-22  84009.532918
31  2025-03-23  83793.308542
32  2025-03-24  85787.709149
33  2025-03-25  87327.729697
34  2025-03-26  87520.583915
35  2025-03-27  86960.855549
36  2025-03-28  87227.271580
37  2025-03-29  84359.469155
38  2025-03-30  82679.172554
39  2025-03-31  82356.381112

query4 Find the coin with the highest average price over 1 year.

In [33]:
pd.read_sql("SELECT coin_id,AVG(price_usd) AS avg_price from hist_prices where date >= CURDATE() - INTERVAL 1 YEAR group by coin_id order by avg_price desc limit 1",engine)

   coin_id     avg_price
0  bitcoin  99697.943747

query5 Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025.

In [34]:
import pandas as pd

In [35]:
#######doubt
pd.read_sql("""
SELECT 
    ((MAX(price_usd) - MIN(price_usd)) / MIN(price_usd)) * 100 AS pct_change
FROM hist_prices
WHERE coin_id = 'bitcoin'
AND date BETWEEN '2024-09-01' AND '2025-09-01';
""", engine)

   pct_change
0   61.879295

part-III oil_prices
QUERY1 Find the highest oil price in the last 5 years.

In [36]:
pd.read_sql("SHOW COLUMNS FROM oil_price", engine)

   Field    Type Null  Key Default Extra
0  index  bigint  YES  MUL    None
1   Date    text  YES         None
2  Price  double  YES         None

In [37]:
pd.read_sql("select max(price) as highest_price from  oil_price where date >= CURDATE() - interval 5 year",engine)

   highest_price
0         123.64

query2 Get the average oil price per year.

In [38]:
pd.read_sql("select year(date) AS year, avg(price) AS avg_price from oil_price group by year(date) order by year",engine)

   year  avg_price
0  2020  39.160437
1  2021  68.135100
2  2022  94.902869
3  2023  77.576532
4  2024  76.632240
5  2025  65.388105
6  2026  60.037000

query3 Show oil prices during COVID crash (March–April 2020).

In [39]:
pd.read_sql("select date, price FROM oil_price WHERE date BETWEEN '2020-03-01' AND '2020-04-30' ORDER BY date",engine)

          date  price
0   2020-03-02  46.78
1   2020-03-03  47.27
2   2020-03-04  46.78
3   2020-03-05  45.90
4   2020-03-06  41.14
5   2020-03-09  31.05
6   2020-03-10  34.47
7   2020-03-11  33.13
8   2020-03-12  31.56
9   2020-03-13  31.72
10  2020-03-16  28.96
11  2020-03-17  26.96
12  2020-03-18  20.48
13  2020-03-19  25.09
14  2020-03-20  19.48
15  2020-03-23  23.33
16  2020-03-24  21.03
17  2020-03-25  20.75
18  2020-03-26  16.60
19  2020-03-27  15.48
20  2020-03-30  14.10
21  2020-03-31  20.51
22  2020-04-01  20.28
23  2020-04-02  25.18
24  2020-04-03  28.36
25  2020-04-06  26.21
26  2020-04-07  23.54
27  2020-04-08  24.97
28  2020-04-09  22.90
29  2020-04-13  22.36
30  2020-04-14  20.15
31  2020-04-15  19.96
32  2020-04-16  19.82
33  2020-04-17  18.31
34  2020-04-20 -36.98
35  2020-04-21   8.91
36  2020-04-22  13.64
37  2020-04-23  15.06
38  2020-04-24  15.99
39  2020-04-27  12.17
40  2020-04-28  12.40
41  2020-04-29  15.04
42  2020-04-30  19.23

query4 Find the lowest price of oil in the last 10 years.

In [40]:
pd.read_sql("select MIN(price) AS lowest_price from oil_price where date >= CURDATE() - interval 10 year",engine)

   lowest_price
0        -36.98

query5 Calculate the volatility of oil prices (max-min difference per year).

In [41]:
pd.read_sql("select year(date) AS year,max(price) - min(price) as yearly_volatility from oil_price group by year(date) order by year",engine)

   year  yearly_volatility
0  2020             100.25
1  2021              38.17
2  2022              52.59
3  2023              27.06
4  2024              20.96
5  2025              25.29
6  2026               8.76

part-IV 4️⃣ stock_prices

Query1 Get all stock prices for a given ticker

In [42]:
pd.read_sql("""
SELECT *
FROM stock_prices
WHERE Ticker IN ('^IXIC', '^NSEI', '^GSPC')
ORDER BY Ticker, Date
""", engine)

,index,Date,Open,High,Low,Close,Volume,Ticker
0,0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
1,1,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
2,2,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
3,3,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
4,4,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC
...,...,...,...,...,...,...,...,...
4572,4572,2026-02-02,24796.500000,25108.099609,24679.400391,25088.400391,4.492000e+05,^NSEI
4573,4573,2026-02-03,26308.050781,26341.199219,25641.300781,25727.550781,6.373000e+05,^NSEI
4574,4574,2026-02-04,25675.050781,25818.550781,25563.949219,25776.000000,4.298000e+05,^NSEI
4575,4575,2026-02-05,25755.900391,25757.650391,25579.500000,25642.800781,3.438000e+05,^NSEI
4576,4576,2026-02-06,25605.800781,25703.949219,25491.900391,25693.699219,3.755000e+05,^NSEI

query 2 Find the highest closing price for NASDAQ (^IXIC)

In [43]:
pd.read_sql("""
SELECT MAX(Close) AS highest_closing_price
FROM stock_prices
WHERE Ticker = '^IXIC'
""", engine)

   highest_closing_price
0           23958.470703

query 3 List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)

In [44]:
pd.read_sql("""
SELECT 
    Date,
    High,
    Low,
    (High - Low) AS price_difference
FROM stock_prices
WHERE Ticker = '^GSPC'
ORDER BY price_difference DESC
LIMIT 5
""", engine)

         Date         High          Low  price_difference
0  2025-04-09  5481.339844  4948.430176        532.909668
1  2025-04-07  5246.569824  4835.040039        411.529785
2  2025-04-08  5267.470215  4910.419922        357.050293
3  2025-04-10  5353.149902  5115.270020        237.879883
4  2025-11-20  6770.350098  6534.049805        236.300293

query 4 Get monthly average closing price for each ticker

In [45]:
pd.read_sql("""
SELECT 
    Ticker,
    YEAR(Date) AS year,
    MONTH(Date) AS month,
    AVG(Close) AS avg_monthly_close
FROM stock_prices
GROUP BY 
    Ticker, YEAR(Date), MONTH(Date)
ORDER BY 
    Ticker, year, month
""", engine)

    Ticker  year  month  avg_monthly_close
0    ^GSPC  2020      1        3278.202858
1    ^GSPC  2020      2        3277.314183
2    ^GSPC  2020      3        2652.393632
3    ^GSPC  2020      4        2761.975226
4    ^GSPC  2020      5        2919.608484
..     ...   ...    ...                ...
217  ^NSEI  2025     10       25494.083519
218  ^NSEI  2025     11       25894.834396
219  ^NSEI  2025     12       25997.738725
220  ^NSEI  2026      1       25652.962695
221  ^NSEI  2026      2       25585.690234

[222 rows x 4 columns]

Query 5 Get average trading volume of NSEI in 2024

In [46]:
pd.read_sql("""
SELECT AVG(Volume) AS avg_trading_volume_2024
FROM stock_prices
WHERE Ticker = '^NSEI'
AND YEAR(Date) = 2024
""", engine)

   avg_trading_volume_2024
0            313560.162602

    Join Queries (Cross-Market Analysis)

Compare Bitcoin vs Oil average price in 2025.

In [47]:
pd.read_sql("""
SELECT 
    AVG(hp.price_usd) AS btc_avg,
    AVG(op.price) AS oil_avg
FROM hist_prices hp
JOIN oil_price op 
    ON hp.date = op.date
WHERE hp.coin_id = 'bitcoin'
""", engine)

        btc_avg    oil_avg
0  101277.85858  63.713051

query 2 Check if Bitcoin moves with S&P 500 (correlation idea).

In [48]:
df=pd.read_sql("""
SELECT 
    hp.date,
    hp.price_usd AS btc_price,
    sp.Close AS sp500_close
FROM hist_prices hp
JOIN stock_prices sp
    ON DATE(hp.date) = sp.Date
WHERE hp.coin_id = 'bitcoin'
AND sp.Ticker = '^GSPC'
ORDER BY hp.date
""", engine)

df['btc_return'] = df['btc_price'].pct_change()
df['sp500_return'] = df['sp500_close'].pct_change()

correlation = df[['btc_return', 'sp500_return']].corr()

print("Correlation:", correlation)

Correlation:               btc_return  sp500_return
btc_return      1.000000     -0.012182
sp500_return   -0.012182      1.000000

Query3 Compare Ethereum and NASDAQ daily prices for 2025.

In [49]:
pd.read_sql("""
SELECT hp.date,
       hp.price_usd AS ethereum_price,
       sp.close AS nasdaq_close
FROM hist_prices hp
JOIN Stock_prices sp
ON hp.date = sp.date
WHERE hp.coin_id = 'ethereum'
AND sp.ticker = '^IXIC'
AND YEAR(hp.date) = 2025""",engine)

           date  ethereum_price  nasdaq_close
0    2025-02-20     2714.801836  19962.359375
1    2025-02-21     2741.593363  19524.009766
2    2025-02-24     2827.184408  19286.929688
3    2025-02-25     2503.103420  19026.390625
4    2025-02-26     2495.315452  19075.259766
..          ...             ...           ...
213  2025-12-24     2965.193660  23613.310547
214  2025-12-26     2904.252345  23593.099609
215  2025-12-29     2947.859761  23474.349609
216  2025-12-30     2934.215602  23419.080078
217  2025-12-31     2970.055474  23241.990234

[218 rows x 3 columns]

Query 4 Find days when oil price spiked and compare with Bitcoin price change.

In [6]:
pd.read_sql("""SELECT 
    o1.date AS market_date,
    o1.price AS oil_price,
    (o1.price - o2.price) AS oil_price_spike,
    hp.price_usd AS bitcoin_price
FROM oil_price o1
JOIN oil_price o2 
    ON o1.date = DATE_ADD(o2.date, INTERVAL 1 DAY)
JOIN hist_prices hp
    ON DATE(hp.date) = o1.date
WHERE hp.coin_id = 'bitcoin'
ORDER BY oil_price_spike DESC
LIMIT 20""",engine)

   market_date  oil_price  oil_price_spike  bitcoin_price
0   2025-06-13      73.84             5.11  105979.229024
1   2025-06-11      68.91             3.25  110212.732521
2   2025-10-23      62.44             3.14  107618.426672
3   2025-06-17      75.62             3.09  106951.272018
4   2025-04-09      62.63             2.59   76329.090356
5   2025-07-29      70.27             2.46  118003.302016
6   2025-04-17      65.07             2.19   84105.779422
7   2026-01-29      64.77             2.02   89162.097016
8   2025-07-02      68.66             2.02  105613.399742
9   2025-05-06      60.42             1.92   94758.823711
10  2025-07-11      69.63             1.85  115879.650301
11  2025-05-08      61.25             1.83   97026.493770
12  2025-02-27      70.62             1.75   83900.114965
13  2026-01-08      57.74             1.73   91257.155440
14  2025-05-13      65.04             1.72  102876.830429
15  2025-09-24      65.40             1.64  112022.165879
16  2025-07-17      68.76             1.63  118748.162737
17  2026-01-27      62.04             1.58   88307.861207
18  2026-01-23      60.70             1.46   89443.397441
19  2026-01-13      60.85             1.46   91134.969180

query 5 Compare top 3 coins daily price trend vs Nifty (^NSEI).

In [51]:
pd.read_sql("""
SELECT hp.coin_id,
       DATE(hp.date) AS date,
       hp.price_usd,
       sp.Close AS nifty_close
FROM hist_prices hp

JOIN (
    SELECT id
    FROM records
    ORDER BY market_cap DESC
    LIMIT 3
) top_coins
ON hp.coin_id = top_coins.id

JOIN stock_prices sp
ON DATE(hp.date) = sp.Date

WHERE sp.Ticker = '^NSEI'
ORDER BY date
""", engine)

      coin_id        date     price_usd   nifty_close
0      tether  2025-02-20      0.999900  22913.150391
1    ethereum  2025-02-20   2714.801836  22913.150391
2     bitcoin  2025-02-20  96554.871563  22913.150391
3      tether  2025-02-21      1.000159  22795.900391
4    ethereum  2025-02-21   2741.593363  22795.900391
..        ...         ...           ...           ...
706  ethereum  2026-02-05   2152.087012  25642.800781
707   bitcoin  2026-02-05  73172.292032  25642.800781
708    tether  2026-02-06      0.998225  25693.699219
709  ethereum  2026-02-06   1820.569322  25693.699219
710   bitcoin  2026-02-06  62853.690384  25693.699219

[711 rows x 4 columns]

query 6 Compare stock prices (^GSPC) with crude oil prices on the same dates

In [52]:
df = pd.read_sql("""
SELECT 
    DATE(s.date) AS date,
    s.close AS sp500_price,
    o.price AS oil_price
FROM stock_prices s
JOIN oil_price o
    ON DATE(s.date) = o.date
WHERE s.ticker = '^GSPC'
ORDER BY date
""", engine)

df

            date  sp500_price  oil_price
0     2020-01-02  3257.850098      61.17
1     2020-01-03  3234.850098      63.00
2     2020-01-06  3246.280029      63.27
3     2020-01-07  3237.179932      62.70
4     2020-01-08  3253.050049      59.65
...          ...          ...        ...
1515  2026-01-26  6950.229980      60.46
1516  2026-01-27  6978.600098      62.04
1517  2026-01-28  6978.029785      62.75
1518  2026-01-29  6969.009766      64.77
1519  2026-01-30  6939.029785      64.50

[1520 rows x 3 columns]

query 7 Correlate Bitcoin closing price with crude oil closing price (same date)

In [53]:
df=pd.read_sql("""SELECT DATE(hp.date) AS date,
       hp.price_usd AS btc_price,
       o.price AS oil_price
FROM hist_prices hp
JOIN oil_price o
ON DATE(hp.date) = o.date
WHERE hp.coin_id = 'bitcoin'
ORDER BY date""",engine)
print(df.head())
correlation = df["btc_price"].corr(df["oil_price"])
print("Price Correlation:", correlation)

         date     btc_price  oil_price
0  2025-02-20  96554.871563      72.88
1  2025-02-21  98384.317382      70.72
2  2025-02-24  96327.463091      71.06
3  2025-02-25  91396.766869      69.15
4  2025-02-26  88755.769336      68.87
Price Correlation: 0.18655508878678217

Query 8 Compare NASDAQ (^IXIC) with Ethereum price trends

In [54]:
pd.read_sql("""SELECT DATE(hp.date) AS date,
       hp.price_usd AS ethereum_price,
       sp.Close AS nasdaq_close
FROM hist_prices hp
JOIN stock_prices sp
ON DATE(hp.date) = sp.Date
WHERE hp.coin_id = 'ethereum'
AND sp.Ticker = '^IXIC'
ORDER BY date""",engine)

           date  ethereum_price  nasdaq_close
0    2025-02-20     2714.801836  19962.359375
1    2025-02-21     2741.593363  19524.009766
2    2025-02-24     2827.184408  19286.929688
3    2025-02-25     2503.103420  19026.390625
4    2025-02-26     2495.315452  19075.259766
..          ...             ...           ...
238  2026-02-02     2269.328852  23592.109375
239  2026-02-03     2344.512261  23255.189453
240  2026-02-04     2226.985636  22904.580078
241  2026-02-05     2152.087012  22540.589844
242  2026-02-06     1820.569322  23031.210938

[243 rows x 3 columns]

Query 9 Join top 3 crypto coins with stock indices for 2025

In [55]:
pd.read_sql("""
SELECT hp.coin_id,
       hp.date,
       hp.price_usd,
       sp.ticker,
       sp.close
FROM hist_prices hp

JOIN (
    SELECT id
    FROM records
    ORDER BY market_cap DESC
    LIMIT 3
) top_coins
ON hp.coin_id = top_coins.id

JOIN Stock_prices sp
ON hp.date = sp.date

WHERE YEAR(hp.date) = 2025
ORDER BY hp.coin_id, hp.date""",engine)

      coin_id        date     price_usd ticker         close
0     bitcoin  2025-02-20  96554.871563  ^GSPC   6117.520020
1     bitcoin  2025-02-20  96554.871563  ^NSEI  22913.150391
2     bitcoin  2025-02-20  96554.871563  ^IXIC  19962.359375
3     bitcoin  2025-02-21  98384.317382  ^GSPC   6013.129883
4     bitcoin  2025-02-21  98384.317382  ^NSEI  22795.900391
...       ...         ...           ...    ...           ...
1939   tether  2025-12-30      0.998916  ^IXIC  23419.080078
1940   tether  2025-12-30      0.998916  ^NSEI  25938.849609
1941   tether  2025-12-31      0.999019  ^GSPC   6845.500000
1942   tether  2025-12-31      0.999019  ^IXIC  23241.990234
1943   tether  2025-12-31      0.999019  ^NSEI  26129.599609

[1944 rows x 5 columns]

Query 10 Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison

In [56]:
pd.read_sql("""
SELECT 
    DATE(hp.date) AS date,
    hp.price_usd AS bitcoin_price,
    op.price AS oil_price,
    sp.Close AS sp500_close
FROM hist_prices hp

JOIN oil_price op
    ON DATE(hp.date) = op.date

JOIN stock_prices sp
    ON DATE(hp.date) = sp.Date

WHERE hp.coin_id = 'bitcoin'
AND sp.Ticker = '^GSPC'

ORDER BY date
""", engine)

           date  bitcoin_price  oil_price  sp500_close
0    2025-02-20   96554.871563      72.88  6117.520020
1    2025-02-21   98384.317382      70.72  6013.129883
2    2025-02-24   96327.463091      71.06  5983.250000
3    2025-02-25   91396.766869      69.15  5955.250000
4    2025-02-26   88755.769336      68.87  5956.060059
..          ...            ...        ...          ...
231  2026-01-26   86548.322135      60.46  6950.229980
232  2026-01-27   88307.861207      62.04  6978.600098
233  2026-01-28   89204.222396      62.75  6978.029785
234  2026-01-29   89162.097016      64.77  6969.009766
235  2026-01-30   84570.409061      64.50  6939.029785

[236 rows x 4 columns]